spring:
    datasource:
        url: jdbc:mysql://localhost:3306/grupo-19-oo2
        username: root
        password: sasa
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        properties:
            dialect: org.hibernate.dialect.MySQL8Dialect