spring:
    datasource:
        url: jdbc:mysql://localhost:3306/grupo-19-oo2
        username: root
        password: 2002
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            dialect: org.hibernate.dialect.MySQL8Dialect